// Decks live on disk as markdown you can open in any editor, with one sidecar
// file holding what the critic found. The markdown is the source of truth and
// the sidecar is disposable: delete it and you lose your dismissals, not your
// slides.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import type { Finding } from "./critic.ts";
import { TEMPLATE, parse, slideKey } from "./outline.ts";

export const HOME = process.env.FEYNMAN_SLIDES_HOME ?? join(homedir(), ".feynman-slides");
export const DECKS = join(HOME, "decks");

export type State = {
  /** Open findings, keyed by slide. Replaced wholesale each time a slide is reviewed. */
  findings: Record<string, Finding[]>;
  /** Rejections, kept forever so a restarted critic is told about them again. */
  dismissed: Finding[];
};

const EMPTY: State = { findings: {}, dismissed: [] };

export function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 60) || "deck"
  );
}

const dir = (slug: string) => join(DECKS, slug);
export const outlinePath = (slug: string) => join(dir(slug), "outline.md");
const statePath = (slug: string) => join(dir(slug), "critiques.json");

export function list(): { slug: string; title: string }[] {
  if (!existsSync(DECKS)) return [];
  return readdirSync(DECKS, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(outlinePath(e.name)))
    .map((e) => {
      const first = readFileSync(outlinePath(e.name), "utf8").split("\n")[0] ?? "";
      return { slug: e.name, title: first.startsWith("# ") ? first.slice(2).trim() : e.name };
    });
}

export function create(title: string): string {
  const slug = slugify(title);
  mkdirSync(dir(slug), { recursive: true });
  if (!existsSync(outlinePath(slug))) {
    writeFileSync(outlinePath(slug), TEMPLATE.replace("{title}", title));
  }
  return slug;
}

export function readOutline(slug: string): string {
  return existsSync(outlinePath(slug)) ? readFileSync(outlinePath(slug), "utf8") : "";
}

export function writeOutline(slug: string, text: string): void {
  mkdirSync(dir(slug), { recursive: true });
  writeFileSync(outlinePath(slug), text);
}

export function readState(slug: string): State {
  const p = statePath(slug);
  if (!existsSync(p)) return structuredClone(EMPTY);
  try {
    const parsed = JSON.parse(readFileSync(p, "utf8"));
    return { findings: parsed.findings ?? {}, dismissed: parsed.dismissed ?? [] };
  } catch {
    // A corrupt sidecar must never cost you your slides, and it holds nothing
    // that cannot be regenerated by writing in the slide again.
    return structuredClone(EMPTY);
  }
}

export function writeState(slug: string, state: State): void {
  mkdirSync(dir(slug), { recursive: true });
  writeFileSync(statePath(slug), JSON.stringify(state, null, 2) + "\n");
}

/**
 * Drop findings for slides that no longer exist.
 *
 * Without this, deleting or renaming a slide leaves its findings holding the
 * export forever, and the critique pane cannot show you what is blocking you
 * because it has no slide to show it under. Rewriting a slide's title is the
 * common case, since the title is part of the key.
 */
export function prune(slug: string, state: State): State {
  const live = new Set(parse(readOutline(slug)).slides.map(slideKey));
  for (const key of Object.keys(state.findings)) {
    if (!live.has(key)) delete state.findings[key];
  }
  return state;
}

/**
 * What stands between you and an export.
 *
 * Errors AND jargon both block, deliberately. Naming a thing instead of
 * explaining it is the failure the Feynman technique exists to catch, and it
 * is the one that feels most like understanding while you are doing it.
 */
export function blocking(state: State): Finding[] {
  return Object.values(state.findings)
    .flat()
    .filter((f) => !f.dismissed && (f.severity === "error" || f.severity === "jargon"));
}
